# Generated by Django 5.0.6 on 2024-05-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=200)),
                ('data', models.TextField()),
            ],
        ),
    ]
